export interface CountryDef {
  code: string;
  name: string;
  currency: string;
  phoneCode: string;
}

export const COUNTRIES: CountryDef[] = [
  { code: "US", name: "United States", currency: "USD", phoneCode: "+1" },
  { code: "PK", name: "Pakistan", currency: "PKR", phoneCode: "+92" },
  { code: "GB", name: "United Kingdom", currency: "GBP", phoneCode: "+44" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", phoneCode: "+971" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", phoneCode: "+966" },
  { code: "IN", name: "India", currency: "INR", phoneCode: "+91" },
  { code: "CA", name: "Canada", currency: "CAD", phoneCode: "+1" },
  { code: "AU", name: "Australia", currency: "AUD", phoneCode: "+61" },
  { code: "DE", name: "Germany", currency: "EUR", phoneCode: "+49" },
  { code: "FR", name: "France", currency: "EUR", phoneCode: "+33" },
  { code: "IT", name: "Italy", currency: "EUR", phoneCode: "+39" },
  { code: "ES", name: "Spain", currency: "EUR", phoneCode: "+34" },
  { code: "NL", name: "Netherlands", currency: "EUR", phoneCode: "+31" },
  { code: "TR", name: "Turkey", currency: "TRY", phoneCode: "+90" },
  { code: "EG", name: "Egypt", currency: "EGP", phoneCode: "+20" },
  { code: "QA", name: "Qatar", currency: "QAR", phoneCode: "+974" },
  { code: "KW", name: "Kuwait", currency: "KWD", phoneCode: "+965" },
  { code: "BH", name: "Bahrain", currency: "BHD", phoneCode: "+973" },
  { code: "OM", name: "Oman", currency: "OMR", phoneCode: "+968" },
  { code: "NG", name: "Nigeria", currency: "NGN", phoneCode: "+234" },
  { code: "ZA", name: "South Africa", currency: "ZAR", phoneCode: "+27" },
  { code: "KE", name: "Kenya", currency: "KES", phoneCode: "+254" },
  { code: "SG", name: "Singapore", currency: "SGD", phoneCode: "+65" },
  { code: "MY", name: "Malaysia", currency: "MYR", phoneCode: "+60" },
  { code: "ID", name: "Indonesia", currency: "IDR", phoneCode: "+62" },
  { code: "TH", name: "Thailand", currency: "THB", phoneCode: "+66" },
  { code: "PH", name: "Philippines", currency: "PHP", phoneCode: "+63" },
  { code: "BD", name: "Bangladesh", currency: "BDT", phoneCode: "+880" },
  { code: "JP", name: "Japan", currency: "JPY", phoneCode: "+81" },
  { code: "KR", name: "South Korea", currency: "KRW", phoneCode: "+82" },
  { code: "CN", name: "China", currency: "CNY", phoneCode: "+86" },
  { code: "BR", name: "Brazil", currency: "BRL", phoneCode: "+55" },
  { code: "MX", name: "Mexico", currency: "MXN", phoneCode: "+52" },
];

export const TIMEZONES = [
  "UTC",
  "America/New_York",
  "America/Chicago",
  "America/Denver",
  "America/Los_Angeles",
  "America/Toronto",
  "America/Sao_Paulo",
  "Europe/London",
  "Europe/Paris",
  "Europe/Berlin",
  "Europe/Madrid",
  "Europe/Rome",
  "Europe/Amsterdam",
  "Europe/Istanbul",
  "Asia/Dubai",
  "Asia/Karachi",
  "Asia/Kolkata",
  "Asia/Dhaka",
  "Asia/Bangkok",
  "Asia/Singapore",
  "Asia/Hong_Kong",
  "Asia/Shanghai",
  "Asia/Tokyo",
  "Asia/Seoul",
  "Asia/Riyadh",
  "Asia/Qatar",
  "Asia/Kuwait",
  "Australia/Sydney",
  "Australia/Melbourne",
  "Africa/Cairo",
  "Africa/Lagos",
  "Africa/Johannesburg",
  "Africa/Nairobi",
];
