import { CanonicalField, CanonicalFieldDefinition } from "./types";

export const CANONICAL_FIELDS: CanonicalFieldDefinition[] = [
  {
    key: "name",
    label: "Product Name",
    description: "Primary product identity/title (Required)",
    required: true,
    type: "string",
    aliases: [
      "product name",
      "product",
      "name",
      "item name",
      "item",
      "item description",
      "product description",
      "product title",
      "title",
      "product_name",
      "item_name",
      "description",
      "articulo",
      "nom",
      "goods name",
      "medicine name",
      "drug name",
    ],
  },
  {
    key: "internal_sku",
    label: "SKU / Item Code",
    description: "Internal inventory SKU or product code",
    required: false,
    type: "string",
    aliases: [
      "sku",
      "internal sku",
      "item code",
      "product code",
      "item no",
      "item number",
      "product id",
      "item id",
      "product no",
      "internal code",
      "code",
      "item_code",
      "product_code",
      "ref",
      "reference",
      "model",
      "part number",
      "part no",
      "catalog no",
    ],
  },
  {
    key: "purchase_cost",
    label: "Purchase Price",
    description: "Buying cost / purchase rate per unit",
    required: false,
    type: "number",
    aliases: [
      "cost",
      "cost price",
      "purchase price",
      "buying price",
      "buy rate",
      "purchase rate",
      "buying rate",
      "unit cost",
      "cp",
      "cost_price",
      "purchase_cost",
      "pur rate",
      "pur price",
      "cost per unit",
      "supplier price",
      "wholesale price",
    ],
  },
  {
    key: "retail_price",
    label: "Retail Price",
    description: "Selling price / MRP per unit",
    required: false,
    type: "number",
    aliases: [
      "selling price",
      "sale price",
      "retail",
      "retail price",
      "mrp",
      "price",
      "rate",
      "sale rate",
      "selling rate",
      "unit price",
      "sp",
      "retail_price",
      "selling_price",
      "list price",
      "sales price",
      "consumer price",
    ],
  },
  {
    key: "discount_price",
    label: "Discount",
    description: "Discounted sale price or discount percentage",
    required: false,
    type: "number",
    aliases: [
      "discount",
      "discount price",
      "promo price",
      "offer price",
      "sale discount",
      "cut price",
      "disc",
      "discount_price",
      "discount %",
      "discount rate",
    ],
  },
  {
    key: "stock_units",
    label: "Stock Units",
    description: "Available quantity in inventory",
    required: false,
    type: "number",
    aliases: [
      "qty",
      "quantity",
      "stock",
      "stock units",
      "available",
      "available qty",
      "current stock",
      "on hand",
      "units",
      "balance qty",
      "in stock",
      "count",
      "quantity on hand",
      "physical stock",
      "stock_units",
    ],
  },
  {
    key: "min_stock_alert",
    label: "Min Stock Alert",
    description: "Low-stock warning threshold",
    required: false,
    type: "number",
    aliases: [
      "min stock",
      "min stock alert",
      "reorder level",
      "low stock",
      "min qty",
      "minimum quantity",
      "minimum stock",
      "safety stock",
      "alert qty",
      "threshold",
      "reorder point",
      "min_stock_alert",
    ],
  },
  {
    key: "category",
    label: "Primary Category",
    description: "Main business category or department",
    required: false,
    type: "category",
    aliases: [
      "category",
      "primary category",
      "department",
      "group",
      "product group",
      "section",
      "family",
      "class",
      "main category",
      "parent category",
      "cat",
    ],
  },
  {
    key: "subcategory",
    label: "Subcategory",
    description: "Specific sub-classification",
    required: false,
    type: "category",
    aliases: [
      "subcategory",
      "sub category",
      "sub-category",
      "sub group",
      "sub department",
      "type",
      "sub type",
      "child category",
      "subcat",
    ],
  },
  {
    key: "uom",
    label: "Unit of Measure (UOM)",
    description: "Base stock unit (e.g. tablet, bottle, piece, kg, liter)",
    required: false,
    type: "string",
    aliases: [
      "uom",
      "unit",
      "unit of measure",
      "base unit",
      "stock unit",
      "measurement unit",
      "measure",
      "uom name",
      "unit type",
      "base uom",
    ],
  },
  {
    key: "packaging",
    label: "Packaging Type",
    description: "Outer package container (e.g. Box, Strip, Bottle, Carton, Pack)",
    required: false,
    type: "string",
    aliases: [
      "packaging",
      "package",
      "package type",
      "container",
      "packing",
      "packaging type",
      "box type",
    ],
  },
  {
    key: "pack_size",
    label: "Pack Size / Units per Pack",
    description: "Number of base units in one package (e.g. 20, 100)",
    required: false,
    type: "number",
    aliases: [
      "pack size",
      "units per pack",
      "units per package",
      "pack qty",
      "packing size",
      "units/pack",
      "qty per pack",
      "items per pack",
    ],
  },
  {
    key: "strength",
    label: "Strength / Formulation",
    description: "Dosage strength or power (e.g. 500mg, 10mg/5ml, 25W)",
    required: false,
    type: "string",
    aliases: [
      "strength",
      "dosage",
      "formulation",
      "potency",
      "power",
      "dose",
      "mg",
      "dosage strength",
    ],
  },
  {
    key: "brand",
    label: "Brand / Manufacturer",
    description: "Brand name, manufacturer, or vendor label",
    required: false,
    type: "string",
    aliases: [
      "brand",
      "manufacturer",
      "mfg",
      "maker",
      "company",
      "vendor name",
      "brand name",
      "make",
    ],
  },
  {
    key: "barcode",
    label: "Global BarCode",
    description: "EAN / UPC / GTIN barcode number",
    required: false,
    type: "string",
    aliases: [
      "barcode",
      "global barcode",
      "ean",
      "upc",
      "gtin",
      "ean13",
      "ean-13",
      "ean8",
      "ean-8",
      "upc code",
      "bar code",
      "codebar",
      "isbn",
      "sku barcode",
    ],
  },
  {
    key: "batch_number",
    label: "Batch Number",
    description: "Manufacturing batch / lot identifier",
    required: false,
    type: "string",
    aliases: [
      "batch",
      "batch number",
      "batch no",
      "batch_number",
      "lot",
      "lot no",
      "lot number",
      "batch/lot",
      "manufacturing batch",
    ],
  },
  {
    key: "expiry_date",
    label: "Expiry Date",
    description: "Product expiration or best-before date",
    required: false,
    type: "date",
    aliases: [
      "expiry",
      "expiry date",
      "expiration",
      "expiration date",
      "exp date",
      "exp",
      "best before",
      "use by",
      "valid till",
      "expiry_date",
      "shelf life",
    ],
  },
  {
    key: "images",
    label: "Product Images",
    description: "Image URL(s) separated by comma or pipe",
    required: false,
    type: "images",
    aliases: [
      "image",
      "images",
      "image url",
      "image urls",
      "product image",
      "product images",
      "photo",
      "picture",
      "image link",
      "image_url",
      "img",
      "thumbnail",
    ],
  },
  {
    key: "metadata",
    label: "MetaData / Description",
    description: "Product notes, specifications, color, size, pack size",
    required: false,
    type: "json",
    aliases: [
      "metadata",
      "meta",
      "notes",
      "remarks",
      "specifications",
      "details",
      "attributes",
      "size",
      "color",
      "weight",
      "material",
      "pack size",
      "variant",
      "model no",
      "extra",
    ],
  },
  {
    key: "status",
    label: "Status",
    description: "Active, Draft, or Archived",
    required: false,
    type: "status",
    aliases: ["status", "state", "product status", "active status"],
  },
  {
    key: "ignore",
    label: "— Ignore Column —",
    description: "Do not import this column",
    required: false,
    type: "string",
    aliases: [
      "ignore",
      "vendor address",
      "supplier phone",
      "internal notes",
      "created by",
      "created at",
      "updated at",
      "timestamp",
    ],
  },
];
